export const FETCH_CABELEIREIROS = "FETCH_CABELEIREIROS";
export const FETCH_CABELEIREIRO = "FETCH_CABELEIREIRO";
export const CREATE_CABELEIREIRO = "CREATE_CABELEIREIRO";
export const DELETE_CABELEIREIRO = "DELETE_CABELEIREIRO";

export const FETCH_CLIENTES = "FETCH_CLIENTES";
export const FETCH_CLIENTE = "FETCH_CLIENTE";
export const CREATE_CLIENTE = "CREATE_CLIENTE";
export const DELETE_CLIENTE = "DELETE_CLIENTE";

export const FETCH_PRODUTOS = "FETCH_PRODUTOS";
export const FETCH_PRODUTO = "FETCH_PRODUTO";
export const CREATE_PRODUTO = "CREATE_PRODUTO";
export const DELETE_PRODUTO = "DELETE_PRODUTO";

export const FETCH_SERVICOS = "FETCH_SERVICOS";
export const FETCH_SERVICO = "FETCH_SERVICO";
export const CREATE_SERVICO = "CREATE_SERVICO";
export const DELETE_SERVICO = "DELETE_SERVICO";
